[package]
name = "redis-client"
version = "0.1.0"
edition = "2024"

[dependencies]
redis = { version = "0.30.0", features = ["tokio-comp"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"