[package]
name = "axum"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.8"
serde = { version = "1", features = ["derive"] }
tracing-subscriber = { version = "0.3"}
tracing = "0.1"
anyhow = "1.0"